### ISSUE TITLE
Negative values - cursor line on wrong side

### ISSUE THREAD

**Issue by benoitjchevalier** [PredixDev/px-vis-polar#8]
we have a boolean to accept negative values (e.g for dB) but if using the chart in "normal" mode then negative values means opposite side.

However I suspect our extents calculation basically does a [0,max] scenario when it should do a [0, Math.max(Math.abs(min), max)] so that if negative values are absolutely bigger than positive one the drawing doesn't go "out of scope".

example: 

![screen shot 2017-10-19 at 10 10 30 am](https://user-images.githubusercontent.com/3206342/31784322-1b016da4-b4b6-11e7-8bde-a0a719af0eb3.png)

**Comment by benoitjchevalier** [comment]
actually fixed it since I was in there...
small remaining issue: the cursor line gets confused by negative values showing on opposite side:

![screen shot 2017-10-19 at 10 17 54 am](https://user-images.githubusercontent.com/3206342/31784533-e1145b96-b4b6-11e7-936d-c3698e5c240a.png)

**Comment by nonmetalhail** [comment]
cursor fixed in pointtooltip branch of vis.

**Comment by benoitjchevalier** [comment]
Still seeing it on our crosshair demo with the latest register branch
